version: '3.8'

services:
  backend:
    build:
      context: . # Ruta al directorio del backend donde está el Dockerfile
    container_name: sintad-backend
    ports:
      - "8080:8080"  # Mapea el puerto 8080
    networks:
      - app-network
    depends_on:
      - postgres  # Si tu backend depende de PostgreSQL (puedes quitarlo si no lo necesitas)

#  frontend:
#    build:
#      context: ./frontend  # Ruta al directorio del frontend donde está el Dockerfile
#    ports:
#      - "80:80"  # Mapea el puerto 80
#    networks:
#      - app-network
#    depends_on:
#      - backend

  postgres:
    container_name: sintad-db
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: sintad
      POSTGRES_PASSWORD: sintad
      POSTGRES_DB: dbSintadBlog
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge